#' Map uPheno plot
#'
#' Generate multiple kinds of plots summarising mappings of phenotypes and genes
#' between the HPO and various non-human ontologies within uPheno.
#' @param types A character vector of plot types to generate.
#' @param pheno_map_genes_match uPheno cross-species mapping data generated by
#' \link[KGExplorer]{map_upheno_data}.
#' @param subset_db1 A character vector of reference ontologies to subset
#' \code{pheno_map_genes_match} by.
#' @returns A named list of \pkg{ggplot2} objects.
#'
#' @export
#' @examples
#' \dontrun{
#' pheno_map_genes_match <- map_upheno_data()
#' upheno_plots <- plot_upheno(
#'   pheno_map_genes_match = pheno_map_genes_match)
#' }
plot_upheno <- function(pheno_map_genes_match=NULL,
                        subset_db1="HP",
                        types=c("rainplot","scatterplot","heatmap")){
  ## Prepare plot data
  n_phenotypes <- object_db <- subject <-NULL;
  {
    #### Subset data ####
    if(!is.null(subset_db1)) {
      plot_dat <- pheno_map_genes_match[object_db %in% subset_db1,]
      messager(data.table::uniqueN(plot_dat$subject_taxon_label2),"/",
               data.table::uniqueN(pheno_map_genes_match$subject_taxon_label2),
               "species remain after filtering by `subset_db1`.")
    }else {
      plot_dat <- data.table::copy(pheno_map_genes_match)
    }
    ## Only use one phenotype-phenotype per row
    plot_dat <- plot_dat[,.SD[1],by=c("object_db","subject","object_db","object")]
    ## Recompute n_phenotypes
    plot_dat[,n_phenotypes:=data.table::uniqueN(subject),
             by=c("object_db","object_db",
                  "subject_taxon1","subject_taxon2",
                  "subject_taxon_label1","subject_taxon_label2"
             )]
  }
  plots <- list()
  if("rainplot" %in% types){
    plots[["rainplot"]] <- plot_upheno_rainplot(plot_dat = plot_dat)
  }
  if("scatterplot" %in% types){
    plots[["scatterplot"]] <- plot_upheno_scatterplot(plot_dat = plot_dat)
  }
  if("heatmap" %in% types){
    plots[["heatmap"]] <- plot_upheno_heatmap(plot_dat = plot_dat)
  }
  return(plots)
}
