#' Map uPheno plot
#'
#' Generate multiple kinds of plots summarising mappings of phenotypes and genes
#' between the HPO and various non-human ontologies within uPheno.
#' @param types A character vector of plot types to generate.
#' @param pheno_map_genes_match uPheno cross-species mapping data generated by
#' \link[KGExplorer]{map_upheno_data}.
#' @param subset_db1 A character vector of reference ontologies to subset
#' \code{pheno_map_genes_match} by.
#' @returns A named list of \pkg{ggplot2} objects.
#'
#' @export
#' @examples
#' \dontrun{
#' pheno_map_genes_match <- map_upheno_data()
#' upheno_plots <- plot_upheno(
#'   pheno_map_genes_match = pheno_map_genes_match)
#' }
plot_upheno <- function(pheno_map_genes_match=NULL,
                        filters=list(db1="HP",
                                     gene_taxon_label1="Homo sapiens"),
                        types=c("rainplot","scatterplot","heatmap")){
  ## Prepare plot data
  id1 <- n_phenotypes <-NULL;
  {
    #### Subset data ####
    plot_dat <- filter_dt(pheno_map_genes_match, 
                          filters = filters)
    messager(data.table::uniqueN(plot_dat$gene_taxon_label2),"/",
             data.table::uniqueN(pheno_map_genes_match$gene_taxon_label2),
             "species remain after filtering by `subset_db1`.")
    ## Only use one phenotype-phenotype per row
    plot_dat <- plot_dat[,.SD[1],by=c("db1","id1","db2","id2")]
    ## Recompute n_phenotypes
    plot_dat[,n_phenotypes:=data.table::uniqueN(id1),
             by=c("db1","db2",
                  "gene_taxon1","gene_taxon2",
                  "gene_taxon_label1","gene_taxon_label2"
             )]
  }
  plots <- list()
  if("rainplot" %in% types){
    plots[["rainplot"]] <- plot_upheno_rainplot(plot_dat = plot_dat)
  }
  if("scatterplot" %in% types){
    plots[["scatterplot"]] <- plot_upheno_scatterplot(plot_dat = plot_dat)
  }
  if("heatmap" %in% types){
    plots[["heatmap"]] <- plot_upheno_heatmap(plot_dat = plot_dat)
  }
  return(plots)
}
